### ISSUE TITLE
[FR] Possibility to search

### ISSUE THREAD

**Issue by muphblu** [nikashitsa/meming-blog#1]
# Ability to search templates.
## Example
For example: add overload for existing context mem creation
### Existing: 
`@memingbot top_text. bottom_text`
### New additional overload: 
`@memingbot top_text. bottom_text. search_string` 
or 
`@memingbot top_text. bottom_text. search_string`

**Comment by muphblu** [comment]
Didn't find bot repository so leave it here

**Comment by nikashitsa** [comment]
@muphblu thank you for your suggestion. Looks good for single language.
But how should it work, if language is set to not english? (bot supports 6 languages for now)
Also, I don't feel that most of bot users know meme names. Even I don't know 😊
