### ISSUE TITLE
UX issue with tg:// links not being proper handled by browsers (ie. add new img, join support)

### ISSUE THREAD

**Issue by mariobaldini** [nikashitsa/meming-blog#2]
Greetings, 

AWSOME bot!

When I try to add a new meme from the memingbot.ml or join the support group the browser is pointed to a tg://.... url. This URL is not being properly handled by my browser (Firefox Nightly or Chrome, in Linux Mint 18.2). So I get a 'not found' site and can not proceed. 

How can I manually add a new meme directly in the TG? Or joing the group, based on the provided link?

I know it's more of a Telegram specific question (or Browser, about handling URLs), but I could not find the proper answer in TG docs and it's really hurting meminbot UX. 

Maybe a "/add-by-code" command to the bot could be useful. The listed memes in the page could have an associated tag (eg. "tech impaired duck"); and  the "/add-by-code" could to a search in the available memes to be installed. 

[]'s

PS: Since I'm opening a support request, it would be fair to be called a tech impaired duck. 

![photo_2017-09-14_14-11-48](https://user-images.githubusercontent.com/307335/30429151-b5962e48-9956-11e7-8061-24510421ca8d.jpg)

**Comment by nikashitsa** [comment]
Hi! Thank you for your question 👍   
It's sad that your browser can't handle such links.
 
Here is the trick which can help you:
1. Look at URL of the "ADD TEMPLATE" button on website. For example: https://t.me/memingbot?start=517
2. Send to @memingbot message `/start 517` and template will be added. **517** is the template ID in this example.

**Comment by mariobaldini** [comment]
Thanks! I could add by the /start ID

Would it be difficult to add a search based on the image tag? Just like regular @gif of telegram does. 

@memingbot search TAG
after selection it enters the "creation mode" with that image.

That would make it very easier to use. 


![photo_2017-09-14_14-36-53](https://user-images.githubusercontent.com/307335/30430226-d3e94e4e-995a-11e7-80dd-db9ad8b3943c.jpg)

**Comment by nikashitsa** [comment]
No problem 😊   
Good idea! I will think about it. Thank you!
